[theme]
primaryColor = "#4CAF50"  # Green
backgroundColor = "#121212"  # Dark background
secondaryBackgroundColor = "#1E1E1E"  # Slightly lighter dark
textColor = "#FFFFFF"  # White text
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
